add_subdirectory(core)
add_subdirectory(utilities)
add_subdirectory(ffmpeg)
add_subdirectory(media)
add_subdirectory(decoder)
add_subdirectory(video)
add_subdirectory(audio)
add_subdirectory(subtitles)
add_subdirectory(rendering)
add_subdirectory(streaming)
add_subdirectory(playlist)
add_subdirectory(metadata)
add_subdirectory(platform)
